=== mvadlja/Nanokinetik-CVImport/Ready!/AspNetUI/App_Data/Locations.xsd
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xs:schema id="Locations" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://locations" xmlns="http://locations" targetNamespace="http://locations" elementFormDefault="qualified">
  <xs:complexType name="Location">
    <xs:sequence>
      <xs:element name="Location" type="Location" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="LogicalUniqueName" type="xs:string" use="required" />
    <xs:attribute name="RowId" type="xs:unsignedByte" use="required" />
    <xs:attribute name="Active" type="xs:boolean" use="required" />
    <xs:attribute name="DisplayName" type="xs:string" use="required" />
    <xs:attribute name="NameShort" type="xs:string" use="required" />
    <xs:attribute name="LocationUrl" type="xs:string" use="required" />
    <xs:attribute name="LocationTarget" type="xs:string" use="required" />
    <xs:attribute name="Description" type="xs:string" use="required" />
    <xs:attribute name="Roles" type="xs:string" use="required" />
    <xs:attribute name="Actions" type="xs:string" use="required" />
    <xs:attribute name="GenerateInTopMenu" type="xs:boolean" use="optional" />
    <xs:attribute name="GenerateInTabMenu" type="xs:boolean" use="optional" />
    <xs:attribute name="OldLocation" type="xs:boolean" use="optional" default="false" />
  </xs:complexType>
  <xs:element name="Locations">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Location" type="Location">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mvadlja/Nanokinetik-CVImport/Ready!/AspNetUI/App_Data/Locations.xml
<?xml version="1.0" encoding="utf-8" ?>
<Locations xmlns="http://locations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://locations Locations.xsd">
  <!-- special locations-->
  <Location LogicalUniqueName="Level0-Error" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="Error" NameShort="Error" LocationUrl="~/Views/Error.aspx" Roles="" Description="Error page" LocationTarget="_blank" Actions="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level0-Default" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="Default" NameShort="Default" LocationUrl="~/Views/Default.aspx" Roles="" Description="Default redirect" LocationTarget="_blank" Actions="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level0-RestrictedArea" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="ErrorInfo" NameShort="ErrorInfo" LocationUrl="~/Views/RestrictedAreaView/ErrorInfo.aspx" Roles="" Description="Redirect in case of error" LocationTarget="_self" Actions="" GenerateInTopMenu="false" />

  <!-- OLD Locations-->
  <Location LogicalUniqueName="Level4-APProperties" OldLocation="true" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="Properties" NameShort="Properties" LocationUrl="~/Views/Business/APPropertiesView.aspx" LocationTarget="_self" Description="Properties" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level3-ProductsMGMT" OldLocation="true" RowId="1" Active="true" DisplayName="Products" NameShort="Products" LocationUrl="~/Views/Business/PRODUCTView.aspx?f=l" LocationTarget="_self" Description="Products" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level4-ProductProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="Properties" LocationUrl="~/Views/Business/ProductPKPPropertiesView.aspx" LocationTarget="_self" Description="Product properties" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level3-PharmaceuticalProducts" OldLocation="true" RowId="1" Active="true" DisplayName="Pharmaceutical products" NameShort="PharmaceuticalProducts" LocationUrl="~/Views/Business/PProductView.aspx?f=l" LocationTarget="_self" Description="PharmaceuticalProducts" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level4-PharmaceuticalProductsProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="PharmaceuticalProducts" LocationUrl="~/Views/Business/PharmaceuticalProductProperties.aspx" LocationTarget="_self" Description="PharmaceuticalProductsProperties" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level4-PharmaceuticalProduct" OldLocation="true" RowId="1" Active="true" DisplayName="Pharmaceutical products" NameShort="PharmaceuticalProduct" LocationUrl="~/Views/Business/PharmaceuticalProductView.aspx" LocationTarget="_self" Description="PharmaceuticalProduct" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level3-Projects" OldLocation="true" RowId="1" Active="true" DisplayName="Projects" NameShort="Projects" LocationUrl="~/Views/Business/PROJECTView.aspx" LocationTarget="_self" Description="Projects" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-NewProduct" OldLocation="true" RowId="1" Active="true" DisplayName="Product" NameShort="Products" LocationUrl="~/Views/Business/PRODUCTView.aspx?f=dn" LocationTarget="_self" Description="Products" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-NewPharmaceuticalProduct" OldLocation="true" RowId="1" Active="true" DisplayName="Pharmaceutical product" NameShort="PharmaceuticalProducts" LocationUrl="~/Views/Business/PProductView.aspx?f=dn" LocationTarget="_self" Description="Products" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-Tasks" OldLocation="true" RowId="1" Active="true" DisplayName="Tasks" NameShort="Tasks" LocationUrl="~/Views/Business/TasksView.aspx" LocationTarget="_self" Description="Task" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-TasksSearch" OldLocation="true" RowId="1" Active="true" DisplayName="Tasks" NameShort="Tasks" LocationUrl="~/Views/Business/TaskSearch.aspx" LocationTarget="_self" Description="Products" Actions="" Roles="" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-ATCCode" OldLocation="true" RowId="1" Active="true" DisplayName="ATC code" NameShort="ATCCode" LocationUrl="~/Views/Operational/ATCCodeView.aspx" LocationTarget="_self" Description="AtcCode" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-TypeOld" OldLocation="true" RowId="1" Active="true" DisplayName="Type" NameShort="Type" LocationUrl="~/Views/Operational/TypeView.aspx" LocationTarget="_self" Description="Type" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-SubstanceOld" OldLocatiAlerterViewon="true" RowId="1" Active="true" DisplayName="Substance" NameShort="Substance" LocationUrl="~/Views/Operational/SubstanceView.aspx" LocationTarget="_self" Description="Substance" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-TaskNames" OldLocation="true" RowId="1" Active="true" DisplayName="Task name" NameShort="TaskNames" LocationUrl="~/Views/Operational/TaskNameView.aspx" LocationTarget="_self" Description="Task names" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-TimeUnitNames" OldLocation="true" RowId="1" Active="true" DisplayName="Time Unit name" NameShort="TimeUnitNames" LocationUrl="~/Views/Operational/TimeUnitNameView.aspx" LocationTarget="_self" Description="Time unit names" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-Organisation" OldLocation="true" RowId="1" Active="true" DisplayName="Organisation" NameShort="Organisation" LocationUrl="~/Views/Operational/ORGANIZATIONView.aspx" LocationTarget="_self" Description="Organisation" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level3-PersonOld" OldLocation="true" RowId="1" Active="true" DisplayName="Person" NameShort="Person" LocationUrl="~/Views/Operational/PERSONView.aspx" LocationTarget="_self" Description="Person" Actions="" Roles="admin, Office" GenerateInTopMenu="true" />
  <Location LogicalUniqueName="Level4-ProjectsProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="ProjectProperties" LocationUrl="~/Views/Business/ProjectProperties.aspx" LocationTarget="_self" Description="Projects documents" Actions="" Roles="" GenerateInTopMenu="false"/>
  <Location LogicalUniqueName="Level4-TProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="TaskProperties" LocationUrl="~/Views/Business/TasksProperties.aspx" LocationTarget="_self" Description="Task properties" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level4-TimeProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="TimeProperties" LocationUrl="~/Views/Business/TimeUnitProperties.aspx" LocationTarget="_self" Description="Time" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level4-TimePropertiesAll" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="TimeProperties" LocationUrl="~/Views/Business/TimeUnitProperties.aspx" LocationTarget="_self" Description="Time" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level4-AProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="ActivityProperties" LocationUrl="~/Views/Business/APropertiesView.aspx" LocationTarget="_self" Description="Activity properties" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level3-NewApprovedSubstance" OldLocation="true" RowId="1" Active="true" DisplayName="Approved substance" NameShort="ApprovedSubstances" LocationUrl="~/Views/Operational/ASView.aspx" LocationTarget="_self" Description="ApprovedSubstances" Actions="" Roles="admin, Office" GenerateInTopMenu="true" >
    <Location LogicalUniqueName="Level4-ApprovedSubstanceProperties" OldLocation="true" RowId="1" Active="true" DisplayName="Properties" NameShort="Substance" LocationUrl="~/Views/Operational/ASProperties.aspx" LocationTarget="_self" Description="Substance" Actions="" Roles="admin, Office" GenerateInTopMenu="false" />
  </Location>
  
  <!-- Authorised product -->
  <Location LogicalUniqueName="Level4-APDocuments" OldLocation="true" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="Documents" NameShort="Documents" LocationUrl="~/Views/Business/APDocumentsView.aspx" LocationTarget="_self" Description="Documents" Actions="" Roles="" GenerateInTopMenu="false" />
  <Location LogicalUniqueName="Level4-AuditTrailAP" OldLocation="true" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="Audit trail" NameShort="Audit trail" LocationUrl="~/Views/Business/APAuditTrail.aspx" LocationTarget="_self" Description="Documents" Actions="" Roles="" GenerateInTopMenu="false" />
          
  <!-- Product -->
  <Location LogicalUniqueName="Level4-PDocuments" OldLocation="true" RowId="1" Active="true" GenerateInTabMenu="false" DisplayName="Documents" NameShort="PDocuments" LocationUrl="~/Views/Business/PDocumentsView.aspx" LocationTarget="_self" Description="Product documents" Actions="" Roles="" GenerateInTopMenu="false" />
